#!/bin/sh
set -eu
cd "$(dirname $0)"
cabal install \
  --installdir=./ \
  --jobs=4 \
  --overwrite-policy=always \
  --install-method=copy \
  --write-ghc-environment-files=always
cabal exec -- xmonad --restart
